version: '3'

services:
  websocket-gateway:
    build: .
    environment:
      SANIC_REQUEST_TIMEOUT: 700
      SANIC_RESPONSE_TIMEOUT: 700 
    ports:
      - "8765:8765"
    volumes:
      - ./socketdock:/usr/src/app/socketdock:z
    command: >
      --bindip 0.0.0.0
      --backend loopback
#      --message-uri ${LAMBDA_ENDPOINT}
#      --disconnect-uri ${LAMBDA_DISCONNECT_ENDPOINT}
#      --endpoint ${EXTERNAL_ENDPOINT}

    # Socket Dock Parameters:
    # parser.add_argument('--bindip', default='127.0.0.1')
    # parser.add_argument('--bindport', default=8765)
    # parser.add_argument('--externalhostandport', default="127.0.0.1:8765")
    # parser.add_argument('--backend', default="loopback", choices=["loopback", "http"])
    # parser.add_argument('--message_uri')
    # parser.add_argument('--disconnect_uri')
