version: '3'

services:
  websocket-gateway:
    build: ..
    ports:
      - "8765:8765"
    volumes:
      - ./wait-for-tunnel.sh:/wait-for-tunnel.sh:ro,z
    entrypoint: /wait-for-tunnel.sh
    command: >
      python -m socketdock
      --bindip 0.0.0.0
      --backend http
      --message-uri ${LAMBDA_ENDPOINT}

    # parser.add_argument('--bindip', default='127.0.0.1')
    # parser.add_argument('--bindport', default=8765)
    # parser.add_argument('--externalhostandport', default="127.0.0.1:8765")
    # parser.add_argument('--backend', default="loopback", choices=["loopback", "http"])
    # parser.add_argument('--message_uri')
    # parser.add_argument('--disconnect_uri')

  tunnel:
    image: ghcr.io/indicio-tech/agent-tunnel:latest
    command: -s websocket-gateway:8765 -p 4040 -h ${AGENT_TUNNEL_HOST}
